
// TODO: More Generic
export const USLocale: Record<string, string> = {
    "GO": "Go",
    "BrownA": "Mediterranean Avenue",
    "CommunityChestA": "Community Chest",
    "BrownB": "Baltic Avenue",
    "IncomeTax": "Income Tax",
    "RailroadA": "Reading Railroad",
    "LightBlueA": "Oriental Avenue",
    "ChanceA": "Chance",
    "LightBlueB": "Vermont Avenue",
    "LightBlueC": "Connecticut Avenue",
    "Jail": "Jail",
    "PinkA": "St. Charles Place",
    "ElectricCompany": "Electric Company",
    "PinkB": "States Avenue",
    "PinkC": "Virginia Avenue",
    "RailroadB": "Pennsylyania Railroad",
    "OrangeA": "St. James Place",
    "CommunityChestB": "Community Chest",
    "OrangeB": "Tennessee Avenue",
    "OrangeC": "New York Avenue",
    "FreeParking": "Free Parking",
    "RedA": "Kentucky Avenue",
    "ChanceB": "Chance",
    "RedB": "Indiana Avenue",
    "RedC": "Illinois Avenue",
    "RailroadC": "B & O Railroad",
    "YellowA": "Atlantic Avenue",
    "YellowB": "Ventnor Avenue",
    "Waterworks": "Water Works",
    "YellowC": "Marvin Gardens",
    "GOTOJail": "Go to Jail",
    "GreenA": "Pacific Avenue",
    "GreenB": "North Carolina Avenue",
    "CommunityChestC": "Community Chest",
    "GreenC": "Pennsylyania Avenue",
    "RailroadD": "Short Line",
    "ChanceC": "Chance",
    "DarkBlueA": "Park Place",
    "SuperTax": "Luxury Tax",
    "DarkBlueB": "Boardwalk",
  }